# Generated by Django 4.2.4 on 2023-10-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastrar',
            new_name='cadastro',
        ),
    ]
