# Generated by Django 4.2.4 on 2023-10-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0002_rename_cadastrar_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='conf_senha',
            new_name='senha1',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='senha',
            new_name='senha2',
        ),
    ]
