# Generated by Django 4.2.4 on 2023-11-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0003_rename_conf_senha_cadastro_senha1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cadastro',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
