# Generated by Django 4.2.5 on 2023-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('turma', models.TextField(max_length=255)),
                ('idade', models.CharField(max_length=100)),
            ],
        ),
    ]
