# Generated by Django 4.2.5 on 2023-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0007_buttoncolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ButtonColor',
        ),
    ]
