# Generated by Django 4.2.4 on 2023-11-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0009_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('rh', models.TextField(max_length=255)),
                ('end', models.TextField(max_length=255)),
                ('respons', models.TextField(max_length=255)),
                ('contato', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
