# Generated by Django 4.2.5 on 2023-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0009_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
