# Generated by Django 4.2.5 on 2023-11-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0010_alunos_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('presenca', models.BooleanField()),
            ],
        ),
    ]
