# Generated by Django 4.2.5 on 2023-11-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0010_aluno_delete_alunos'),
        ('app_Synthesi', '0011_presenca'),
    ]

    operations = [
    ]
