# Generated by Django 4.2.5 on 2023-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0012_merge_0010_aluno_delete_alunos_0011_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('turma', models.TextField(max_length=255)),
                ('idade', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.RenameField(
            model_name='presenca',
            old_name='nome_aluno',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='presenca',
            name='presenca',
            field=models.TextField(max_length=255),
        ),
    ]
