# Generated by Django 4.2.5 on 2023-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0013_alunos_delete_aluno_rename_nome_aluno_presenca_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoavaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField(max_length=255)),
            ],
        ),
    ]
