# Generated by Django 4.2.5 on 2023-11-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0015_alunos_contato_alunos_cpf_alunos_end_alunos_respons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='end',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='rh',
        ),
    ]
