# Generated by Django 4.2.5 on 2023-11-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0018_delete_autoavaliacao_alunos_cor_alter_alunos_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='presenca',
        ),
        migrations.AddField(
            model_name='presenca',
            name='status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
