# Generated by Django 4.2.5 on 2023-11-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0020_remove_presenca_status_presenca_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='nome',
        ),
    ]
