# Generated by Django 4.2.5 on 2023-11-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0021_remove_presenca_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
