# Generated by Django 4.2.5 on 2023-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Synthesi', '0023_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='nome',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
